In [1]:
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

In [2]:
random_data = pd.read_csv('randomdata.csv') # Data is not uploaded in Repo for privacy reasons

In [3]:
random_data = random_data.drop(['Timestamp', 'Email Address', 'Name (optional)', 'Gender', 'Age','Occupation'], axis = 1)

In [4]:
random_data.head() # There are 16 variables 

SI_1  SI_2  SI_3  PEB_1  PEB_2  PEB_3  PEB_4  PEB_5  SoIn_1  SoIn_2  \
0     4     4     5      7      7      5      6      7       4       6   
1     7     7     7      7      7      7      7      7       7       7   
2     3     5     4      6      4      3      6      5       4       4   
3     1     2     2      4      4      4      4      3       2       2   
4     3     7     7      7      4      2      4      6       1       1   

   SoIn_3  SoIn_4  SoIn_5  CA_1  CA_2  CA_3  
0       4       4       5     7     7     7  
1       7       7       7     7     7     7  
2       2       4       4     5     4     6  
3       2       2       4     7     2     5  
4       1       5       4     4     7     5

In [5]:
from dpeda import eda, dp

In [6]:
own = eda.Owner()

In [7]:
og_results = own.get_stats(random_data)

In [10]:
print(og_results)  # Actual Mean, Std, Variance of the 16 variables

[[4.73684211 1.91894436 3.68234746]
 [5.02631579 1.70091348 2.89310666]
 [5.07894737 1.82967059 3.34769446]
 [6.20175439 1.14582601 1.31291725]
 [5.51754386 1.37121131 1.88022046]
 [4.52631579 1.55267697 2.41080578]
 [5.83333333 1.35618326 1.83923304]
 [5.03508772 1.65058222 2.72442167]
 [4.72807018 1.97455086 3.89885111]
 [5.09649123 1.6018203  2.56582829]
 [4.07017544 2.06838528 4.27821767]
 [4.51754386 1.92437764 3.70322931]
 [4.72807018 1.8303493  3.35017854]
 [6.01754386 1.31689133 1.73420276]
 [5.64035088 1.49410164 2.2323397 ]
 [6.00877193 1.2515167  1.56629405]]


In [12]:
dp_results = dp.AddNoise(og_results, epsilon = 1)  # Differentially Private Mean, Std, Variance of the 16 variables

In [14]:
dp_results

[array([4.2313067 , 1.41340896, 3.17681206]),
 array([3.87392207, 0.54851976, 1.74071294]),
 array([6.0324871 , 2.78321032, 4.30123419]),
 array([6.6737173 , 1.61778893, 1.78488017]),
 array([ 3.61438356, -0.53194899, -0.02293984]),
 array([5.71049417, 2.73685535, 3.59498416]),
 array([ 3.98595139, -0.49119868, -0.0081489 ]),
 array([7.35583452, 3.97132902, 5.04516847]),
 array([8.20299808, 5.44947877, 7.37377902]),
 array([7.40320843, 3.90853751, 4.87254549]),
 array([ 1.46617636, -0.5356138 ,  1.67421859]),
 array([5.01078098, 2.41761476, 4.19646643]),
 array([5.18863661, 2.29091573, 3.81074497]),
 array([5.1187993 , 0.41814677, 0.83545821]),
 array([5.91184421, 1.76559496, 2.50383303]),
 array([ 4.15093386, -0.60632136, -0.29154401])]

## More details: Coming Soon 