In [1]:
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

In [2]:
random_data = pd.read_csv('randomdata.csv')

In [3]:
print(random_data.columns[0:6])

Index(['Timestamp', 'Email Address', 'Name (optional)', 'Gender', 'Age',
       'Occupation'],
      dtype='object')


In [4]:
random_data = random_data.drop(['Timestamp', 'Email Address', 'Name (optional)', 'Gender', 'Age','Occupation'], axis = 1)

In [5]:
random_data.head()

SI_1  SI_2  SI_3  PEB_1  PEB_2  PEB_3  PEB_4  PEB_5  SoIn_1  SoIn_2  \
0     4     4     5      7      7      5      6      7       4       6   
1     7     7     7      7      7      7      7      7       7       7   
2     3     5     4      6      4      3      6      5       4       4   
3     1     2     2      4      4      4      4      3       2       2   
4     3     7     7      7      4      2      4      6       1       1   

   SoIn_3  SoIn_4  SoIn_5  CA_1  CA_2  CA_3  
0       4       4       5     7     7     7  
1       7       7       7     7     7     7  
2       2       4       4     5     4     6  
3       2       2       4     7     2     5  
4       1       5       4     4     7     5

In [ ]:
profile = ProfileReport(random_data, title='EV Adoption in India', explorative=True )

In [ ]:
profile.to_file("data_report.html")


In [ ]:
profile.to_file("data_report.json")


In [ ]:
import json

In [ ]:
json_file = open('data_report.json')
randomjson = json.load(json_file)
for x in randomjson['variables'].keys():
    dpm = AddNoise(randomjson['variables'][x]['mean'], 1)
    print(f"OG vs DP: {randomjson['variables'][x]['mean'], dpm}")

In [ ]:
# for x in randomjson['variables'].keys():
# #     print(f"OV: {buf['mean']}")
# #     randomjson['variables'][x]['mean'] = AddNoise(randomjson['variables'][x]['mean'] )
# #     print(f"DPV: {randomjson['variables'][x]['mean']}")
#     dpm = AddNoise(randomjson['variables'][x]['mean'], 1)
#     print(f"DPV: {dpm}")
    

In [ ]:
def AddNoise(x, epsilon=0.5):
    x +=  np.random.laplace(0,1.0/epsilon)
    return x

In [ ]:
np.random.laplace(0, 1.0/0.2, 3)

In [ ]:
randomjson['variables']['SI_1'].keys()

In [ ]:
!ls

In [11]:
import dpeda
# from dpeda import eda,dp
dir(dpeda)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'dp',
 'eda']

In [12]:
own = dpeda.eda.Owner()

In [13]:
og_results = own.get_stats(random_data)

In [14]:
og_results  

array([[4.73684211, 1.91894436, 3.68234746],
       [5.02631579, 1.70091348, 2.89310666],
       [5.07894737, 1.82967059, 3.34769446],
       [6.20175439, 1.14582601, 1.31291725],
       [5.51754386, 1.37121131, 1.88022046],
       [4.52631579, 1.55267697, 2.41080578],
       [5.83333333, 1.35618326, 1.83923304],
       [5.03508772, 1.65058222, 2.72442167],
       [4.72807018, 1.97455086, 3.89885111],
       [5.09649123, 1.6018203 , 2.56582829],
       [4.07017544, 2.06838528, 4.27821767],
       [4.51754386, 1.92437764, 3.70322931],
       [4.72807018, 1.8303493 , 3.35017854],
       [6.01754386, 1.31689133, 1.73420276],
       [5.64035088, 1.49410164, 2.2323397 ],
       [6.00877193, 1.2515167 , 1.56629405]])

In [15]:
dpeda.dp.AddNoise(og_results, 1)

[array([4.75908658, 1.94118884, 3.70459194]),
 array([4.24892116, 0.92351885, 2.11571203]),
 array([4.62921852, 1.37994174, 2.89796561]),
 array([6.53172015, 1.47579177, 1.64288301]),
 array([ 3.6439508 , -0.50238175,  0.0066274 ]),
 array([5.50055113, 2.52691231, 3.38504111]),
 array([7.86553721, 3.38838713, 3.87143691]),
 array([4.40027214, 1.01576664, 2.08960609]),
 array([5.08108786, 2.32756855, 4.2518688 ]),
 array([4.92160003, 1.4269291 , 2.39093709]),
 array([4.09189161, 2.09010145, 4.29993383]),
 array([4.51941534, 1.92624913, 3.7051008 ]),
 array([5.95052772, 3.05280684, 4.57263609]),
 array([ 1.75544253, -2.94521   , -2.52789857]),
 array([ 3.50675868, -0.63949056,  0.0987475 ]),
 array([8.81714542, 4.05989019, 4.37466754])]

In [ ]:
for i in range(len(og_results)):
    print(og_results[i])